### PR TITLE
fixed a little bug and made it python3 friendly

### PR DESCRIPTION
**Pull request by Ghoreish**
I just added .encode() in send() function and made added some files to make it python3 friendly.
I hope you like it ;)

### CODE REVIEW

**Review by myelin — CHANGES_REQUESTED** [review]
Thank you!  A request and a question:

There's no need to create separate _python3 versions of the Python files; can you apply the changes to the original files and remove *_python3.py please?

Has this been tested against a current version of Snarl on Windows?  I haven't used it in quite a few years :)

**Comment by Ghoreish** [comment]
Sure I will😉
But I can't test it on snarl because I'm not a pro at snarl.
I'm going to change the original file for python3 and remove the *_python3.py files😉

**Comment by Ghoreish** [comment]
Done :wink:

**Review by myelin — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
